
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@nyfashion.com'
  smtp_auth_username: 'alerts@nyfashion.com'
  smtp_auth_password: 'your_smtp_password'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    repeat_interval: 30m
  - match:
      component: deployment
    receiver: 'deployment-alerts'
    group_wait: 5s
    repeat_interval: 15m
  - match:
      component: database
    receiver: 'database-alerts'
    repeat_interval: 30m

receivers:
- name: 'default'
  email_configs:
  - to: 'ops-team@nyfashion.com'
    subject: 'NY Fashion Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
      {{ end }}

- name: 'critical-alerts'
  email_configs:
  - to: 'ops-team@nyfashion.com,cto@nyfashion.com'
    subject: '[CRITICAL] NY Fashion Alert: {{ .GroupLabels.alertname }}'
    body: |
      🚨 CRITICAL ALERT 🚨
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Component: {{ .Labels.component }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#critical-alerts'
    title: '[CRITICAL] NY Fashion Alert'
    text: |
      {{ range .Alerts }}
      🚨 {{ .Annotations.summary }}
      {{ .Annotations.description }}
      {{ end }}

- name: 'deployment-alerts'
  email_configs:
  - to: 'devops-team@nyfashion.com'
    subject: '[DEPLOYMENT] NY Fashion Alert: {{ .GroupLabels.alertname }}'
    body: |
      🚀 DEPLOYMENT ALERT 🚀
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Environment: {{ .Labels.environment }}
      Deployment ID: {{ .Labels.deployment_id }}
      Time: {{ .StartsAt }}
      {{ end }}
  webhook_configs:
  - url: 'http://nyfashion-app:8080/api/webhooks/deployment-alert'
    send_resolved: true

- name: 'database-alerts'
  email_configs:
  - to: 'dba-team@nyfashion.com,ops-team@nyfashion.com'
    subject: '[DATABASE] NY Fashion Alert: {{ .GroupLabels.alertname }}'
    body: |
      💾 DATABASE ALERT 💾
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Database: {{ .Labels.database }}
      Instance: {{ .Labels.instance }}
      Time: {{ .StartsAt }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
